sudo: required
env:
  matrix:
    - NODE=8
    - NODE=8.11
    - NODE=10
services:
- docker
script:
  - echo $NODE
# - docker build -t stocard/node:$TRAVIS_COMMIT .
# - docker tag stocard/node:$TRAVIS_COMMIT stocard/node:$TRAVIS_BRANCH
# after_success:
# - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push stocard/node:$TRAVIS_COMMIT && docker push stocard/node:$TRAVIS_BRANCH && docker logout
env:
  global:
  - secure: qiWFg23Mmpx+1y4s3SSH5/BmhTSTG2kABgFB52eu3mXqd/eFoJy33zSN/T5+o7JjvEJ/Up4hxfvLCu4bt6n/t8QHkeey4V1ZCp7AI/zpNelK2y1QkBdJUBhORWjUxYGEW0cEmh/NdV0XN58/uXTG8v9rae8JA642+zYXdjUewsKLx/rYrqOwj7ugK/OfPW/9LBSnj/nIXOJdHp9EHnMc5GbXTOqETuBsNdylD567QziEVncJdJYlYw8Aku03aIZ4Brxyr6s7j5lzoN4YM2aW/Tyaybb6+ph7GMZsJd6Fe5u0NrZ8JgV/j4bPfnpaToOUO+DKF8QeaEaff6eboNHmbWwQm5OHz9rGy2zam6qE1PmKs/FEhNa+i2Kn9DD0o88arUVLkk6p8wpBe4TtoYqUd22sBPsJherI1kvQdKcEhhc2X56lqfK1HrNabZaYp7UOoRibdPRyAkcgPR18Y89GEf29TnD9vGfWWd4m+1iCYiaZmxwO1dJ6mabkdc99nkLfH8bH9HM+0v5ZanB91iA7mZcZ6GarcGh4AsY8K8eJEcZWehxk09GS3Q75J9kb7oVnQzquPhYa1DVs0bY/crYcltlgAJnCmlgWuBxYChu1cx2H4JdZFiIR1RpXW5D2NnCaLpueNp5FanFF1CXbgQpwMasGCVIWlmBx27x+wJPwOC4=
  - secure: a6H/g16TG8pegGbLxTgikIF7m3C0aB4k5WmK9XSCFRKSv5WKiu9LfgEbWzsBEc2jAejWaA9w1jQXdX+Zjk6uhW7xk9N/bhche/mPtfQjRTfhDzghqvIXk3fEft7HsWT573+jIwsifbb3ZX5ij99Z9DCD0JHvyGRKiYmjWEcr0vaCat3RfHtaePgu9P94CLfxupd4x9TgBT0nL/XbuIde6NYtYlc85YpD5x9tEegoinFOJfrEnjFlxnu4EJLUF9AB7YcqKLpeDN8QmMj1YKRBTmXEctmc84ls8K8Q7WZFSusdu4Z+hx+t/HZaU5gb1H/JIqFNw22jAXJO9iVXNh+yZINCKbXaaPXRnJ7dfyWO8Uqu1ZkcBMx0mL+JB+6d8x6Q4PcM0gEDsiQeusgm0LAX3MH6MW/AquAftKc7yYHLNo7culURiKoLk3BCdggAi58R90fiABTl8uJtd5fA1DT05U7b63m5nJhWchPlmVU2z0zw9I6JoWXZtXpQMnzV+z+lUVujBqYBF38cEutJrvn9ND/dgeuDtotpFFrTZlD5SgjihC2NUUYOLo2L2OlCYA0AEGte9R5g5k/rcRPeiQDHuXdkKTN0XIHKZDuadUz2LZ6ULH+bRXgn38XZ3O94QbLgevZIzJboSzD271n+AgmLJuxbVvol5iNow1jupd/Ef3c=
