name: Docker Image Build & Test

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        NODE: [8, 8.11, 8.17, 10, 12, 14]

    steps:
    - uses: actions/checkout@v1
    - name: Insert node version into Dockerfile
      run: sed -i "s/{VERSION}/${{ matrix.NODE }}/g" ./Dockerfile
    - name: Build the Docker image
      run: docker build -t stocard/node:${{ matrix.NODE }} .
