name: Docker Image Build & Push

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        NODE: [8, 8.11, 10, 12]

    steps:
    - uses: actions/checkout@v1
    - name: Insert node version into Dockerfile
      run: sed -i "s/{VERSION}/${{ matrix.NODE }}/g" ./Dockerfile
    - name: Build the Docker image
      run: docker build -t stocard/node:${{ matrix.NODE }} .
    - name: Push docker image to dockerhub
      run: docker login -u="${{ secrets.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}" && docker push stocard/node:${{ matrix.NODE }} && docker logout
